# Test your Pastebucket endpoints

GET http://127.0.0.1:3000/
Accept: application/json

###

GET http://127.0.0.1:3000/pastebucket/shiny-fox-123
Accept: text/html

###

# WebSocket tests require a WebSocket client, but you can try the URL:
# ws://127.0.0.1:3000/ws/shiny-fox-123
